FROM eclipse-temurin:17-jre
 
WORKDIR /app
 
# Copy the JAR file
COPY HealthInsurance/target/CrudOperation-0.0.1-SNAPSHOT.jar app.jar
 
# Expose port
EXPOSE 8080
 
# Run the application
CMD ["java", "-jar", "app.jar"]
